//----------------------------------------------------
//--- GAMEGURU - M-LUA-General
//----------------------------------------------------

#include "cstr.h"

void lua_prompt ( void );
void lua_promptduration ( void );
void lua_prompttextsize ( void );
void lua_promptlocal ( void );
void lua_promptlocalforvr ( void );
void lua_prompt3d ( LPSTR pTextToRender, DWORD dwPrompt3DTime );
void lua_positionprompt3d (  float fX, float fY, float fZ, float fAngleY );
void lua_updateprompt3d ( void );
void lua_hideprompt3d ( void );
void lua_freeprompt3d ( void );
void lua_text ( void );
void lua_setfognearest ( void );
void lua_setfogdistance ( void );
void lua_setfogred ( void );
void lua_setfoggreen ( void );
void lua_setfogblue ( void );
void lua_setfogintensity ( void );
void lua_setambienceintensity ( void );
void lua_setambiencered ( void );
void lua_setambiencegreen ( void );
void lua_setambienceblue ( void );
void lua_setsurfaceintensity ( void );
void lua_setsurfacered ( void );
void lua_setsurfacegreen ( void );
void lua_setsurfaceblue ( void );
void lua_setsurfacesunfactor ( void );
void lua_setglobalspecular ( void );
void lua_setbrightness ( void );
void lua_setconstrast ( void );

void lua_setpostbloom ( void );
void lua_setpostvignetteradius ( void );
void lua_setpostvignetteintensity ( void );
void lua_setpostmotiondistance ( void );
void lua_setpostmotionintensity ( void );
void lua_setpostdepthoffielddistance ( void );
void lua_setpostdepthoffieldintensity ( void );
void lua_setpostlightraylength ( void );
void lua_setpostlightrayquality ( void );
void lua_setpostlightraydecay ( void );
void lua_setpostsaoradius ( void );
void lua_setpostsaointensity ( void );
void lua_setpostlensflareintensity ( void );

void lua_setoptionreflection ( void );
void lua_setoptionshadows ( void );
void lua_setoptionlightrays ( void );
void lua_setoptionvegetation ( void );
void lua_setoptionocclusion ( void );
void lua_setcameradistance ( void );
void lua_setcamerafov ( void );
void lua_setcamerazoompercentage ( void );
void lua_setcameraweaponfov ( void );
void lua_setterrainlodnear ( void );
void lua_setterrainlodmid ( void );
void lua_setterrainlodfar ( void );
void lua_setterrainsize ( void );
void lua_setvegetationquantity ( void );
void lua_setvegetationwidth ( void );
void lua_setvegetationheight ( void );

void lua_jumptolevel ( void );
void lua_finishlevel ( void );
void lua_hideterrain ( void );
void lua_showterrain ( void );
void lua_hidewater ( void );
void lua_showwater ( void );
void lua_hidehuds ( void );
void lua_showhuds ( void );
void lua_freezeai ( void );
void lua_unfreezeai ( void );
void lua_freezeplayer ( void );
void lua_unfreezeplayer ( void );
void lua_setfreezepositionx ( void );
void lua_setfreezepositiony ( void );
void lua_setfreezepositionz ( void );
void lua_setfreezepositionax ( void );
void lua_setfreezepositionay ( void );
void lua_setfreezepositionaz ( void );
void lua_transporttofreezeposition ( void );
void lua_activatemouse ( void );
void lua_deactivatemouse ( void );
void lua_setplayerhealth ( void );
void lua_setplayerlives ( void );
void lua_removeplayerweapons ( void );
void lua_disablemusicreset ( void );
void lua_musicload ( void );
void lua_musicsetinterval ( void );
void lua_musicsetlength ( void );
void lua_musicstop ( void );
void lua_musicplayinstant ( void );
void lua_musicplayfade ( void );
void lua_musicplaycue ( void );
void lua_musicplaytime ( void );
void lua_musicplaytimecue ( void );
void lua_musicsetvolume ( void );
void lua_musicsetdefault ( void );
void lua_musicsetfadetime ( void );
void lua_startparticleemitter ( void );
void lua_stopparticleemitter ( void );
void lua_loadimages ( void );
void lua_setimagepositionx ( void );
void lua_setimagepositiony ( void );
void lua_setimagealignment ( void );
void lua_showimage ( void );
void lua_hideimage ( void );

void lua_startgame ( void );
void lua_loadgame ( void );
void lua_savegame ( void );
void lua_quitgame ( void );
void lua_leavegame ( void );
void lua_resumegame ( void );
void lua_switchpage ( void );
void lua_switchpageback ( void );
void lua_levelfilenametoload ( void );
void lua_resetfade ( void );
void lua_triggerfadein ( void );

void lua_setgamequality ( void );
void lua_setplayerfov ( void );
void lua_setgamesoundvolume ( void );
void lua_setgamemusicvolume ( void );
void lua_setloadingresource ( void );
