//========================================================================================
// DBPro Commands
//========================================================================================

#ifndef FPSCR
	#define FPSCR __declspec ( dllexport )
#endif

int PhotonInit();
void PhotonFree();

/*
FPSCR bool PhotonOwned ( void );
FPSCR LPSTR PhotonGetPlayerName(void);
FPSCR LPSTR PhotonGetOtherPlayerName( int index );
FPSCR LPSTR PhotonGetPlayerID(void);
FPSCR void PhotonLoop(void);
FPSCR int PhotonIsOnline(void);
FPSCR void PhotonAddAch(void);
void ParseCommandLine( const char *pchCmdLine, const char **ppchServerAddress, const char **ppchLobbyID, bool *pbUseVR );
void PhotonInitClient();
FPSCR void PhotonCreateLobby();
FPSCR int PhotonIsLobbyCreated();
FPSCR void PhotonGetLobbyList();
FPSCR int PhotonIsLobbyListCreated();
FPSCR int PhotonGetLobbyListSize();
FPSCR LPSTR PhotonGetLobbyListName( int index );
FPSCR void PhotonJoinLobby( int index );
FPSCR int PhotonGetLobbyUserCount();
FPSCR int PhotonHasJoinedLobby();
FPSCR void PhotonStartServer();
FPSCR int PhotonIsServerRunning();
FPSCR int PhotonIsGameRunning();
FPSCR int PhotonGetMyPlayerIndex();
FPSCR void PhotonSetPlayerPositionX( float _x);
FPSCR void PhotonSetPlayerPositionY( float _y );
FPSCR void PhotonSetPlayerPositionZ( float _z );
FPSCR void PhotonSetPlayerAngle( float _angle );
FPSCR void PhotonSetPlayerScore( int index, int score );
FPSCR float PhotonGetPlayerPositionX ( int index );
FPSCR float PhotonGetPlayerPositionY ( int index );
FPSCR float PhotonGetPlayerPositionZ ( int index );
FPSCR float PhotonGetPlayerAngle ( int index );
FPSCR int PhotonGetPlayerScore ( int index );
FPSCR void PhotonSetBullet ( int index , float x , float y , float z, float anglex, float angley, float anglez, int type, int on );
FPSCR int PhotonGetBulletOn ( int index );
FPSCR int PhotonGetBulletType ( int index );
FPSCR float PhotonGetBulletX ( int index );
FPSCR float PhotonGetBulletY ( int index );
FPSCR float PhotonGetBulletZ ( int index );
FPSCR float PhotonGetBulletAngleX ( int index );
FPSCR float PhotonGetBulletAngleY ( int index );
FPSCR float PhotonGetBulletAngleZ ( int index );
FPSCR void PhotonSetKeyState ( int key , int state );
FPSCR int PhotonGetKeyState ( int index, int key );
FPSCR void PhotonApplyPlayerDamage ( int index, int damage, int x, int y, int z, int force, int limb );
FPSCR int PhotonGetPlayerDamageSource();
FPSCR int PhotonGetPlayerDamageX();
FPSCR int PhotonGetPlayerDamageY();
FPSCR int PhotonGetPlayerDamageZ();
FPSCR int PhotonGetPlayerDamageForce();
FPSCR int PhotonGetPlayerDamageLimb();
FPSCR int PhotonGetPlayerKilledSource( int index );
FPSCR int PhotonGetPlayerKilledX( int index );
FPSCR int PhotonGetPlayerKilledY( int index );
FPSCR int PhotonGetPlayerKilledZ( int index );
FPSCR int PhotonGetPlayerKilledForce( int index );
FPSCR int PhotonGetPlayerKilledLimb( int index );
FPSCR void PhotonKilledBy ( int killedBy, int x, int y, int z, int force, int limb );
FPSCR void PhotonKilledSelf();
FPSCR LPSTR PhotonGetServerMessage( void );
FPSCR int PhotonGetPlayerDamageAmount ();
FPSCR int PhotonGetClientServerConnectionStatus();
void PhotonResetClient();
void PhotonCleanupClient();
void ResetGameStats();
FPSCR void PhotonSetPlayerAlive ( int state );
FPSCR int PhotonGetPlayerAlive ( int index );
FPSCR void PhotonSpawnObject ( int obj, int source, float x, float y, float z );
FPSCR void PhotonDeleteObject ( int obj );
FPSCR void PhotonDestroy ( int obj );
FPSCR void PhotonSendLua ( int code, int e, int v );
FPSCR void PhotonSendLuaString ( int code, int e, LPSTR s );
FPSCR int PhotonGetLuaList();
FPSCR void PhotonGetNextLua();
FPSCR int PhotonGetLuaCommand();
FPSCR int PhotonGetLuaE();
FPSCR int PhotonGetLuaV();
FPSCR LPSTR PhotonGetLuaS(void);
FPSCR int PhotonGetSpawnList();
FPSCR void PhotonGetNextSpawn();
FPSCR int PhotonGetSpawnObjectNumber();
FPSCR int PhotonGetSpawnObjectSource();
FPSCR float PhotonGetSpawnX();
FPSCR float PhotonGetSpawnY();
FPSCR float PhotonGetSpawnZ();
FPSCR int PhotonGetDeleteList();
FPSCR void PhotonGetNextDelete();
FPSCR int PhotonGetDeleteObjectNumber();
FPSCR int PhotonGetDeleteSource();
FPSCR int PhotonGetDestroyList();
FPSCR void PhotonGetNextDestroy();
FPSCR int PhotonGetDestroyObjectNumber();
FPSCR int PhotonReadyToSpawn();
FPSCR void PhotonSetSendFileCount(int count);
FPSCR void PhotonSendFileBegin ( int index , LPSTR pString );
FPSCR int PhotonSendFileDone();
FPSCR int PhotonAmIFileSynced();
FPSCR int PhotonIsEveryoneFileSynced();
FPSCR void PhotonSendIAmLoadedAndReady();
FPSCR int PhotonIsEveryoneLoadedAndReady();
FPSCR void PhotonSendIAmReadyToPlay();
FPSCR int PhotonIsEveryoneReadyToPlay();
FPSCR int PhotonGetFileProgress();
FPSCR void PhotonSetVoiceChat( int on );
FPSCR void PhotonSetPlayerAppearance( int a );
FPSCR int PhotonGetPlayerAppearance( int index );
FPSCR void PhotonSetCollision ( int index, int state );
FPSCR int PhotonGetCollisionList();
FPSCR void PhotonGetNextCollision();
FPSCR int PhotonGetCollisionIndex();
FPSCR int PhotonGetCollisionState();
FPSCR void PhotonShoot ();
FPSCR int PhotonGetShoot ( int index );
FPSCR void PhotonPlayAnimation ( int index, int start, int end, int speed );
FPSCR int PhotonGetAnimationList();
FPSCR void PhotonGetNextAnimation();
FPSCR int PhotonGetAnimationIndex();
FPSCR int PhotonGetAnimationStart();
FPSCR int PhotonGetAnimationEnd();
FPSCR int PhotonGetAnimationSpeed();
FPSCR void PhotonSetTweening(int index , int flag);
FPSCR LPSTR PhotonGetLobbyUserName( int index);
FPSCR void PhotonLeaveLobby();
FPSCR void PhotonCreateWorkshopItem();
FPSCR void PhotonCreateWorkshopItem( LPSTR pString );
FPSCR void PhotonDownloadWorkshopItem( LPSTR pString );
FPSCR int PhotonIsWorkshopItemDownloaded();
FPSCR int PhotonIsWorkshopItemUploaded();
FPSCR LPSTR PhotonGetPlayerName(void);
FPSCR LPSTR PhotonGetWorkshopID(void);
FPSCR LPSTR PhotonGetWorkshopItemPath(void);
FPSCR void PhotonGetWorkshopItemPathDLL(LPSTR string );
FPSCR int PhotonIsWorkshopLoadingOnDLL();
FPSCR void PhotonSetRoot(LPSTR string );
FPSCR void PhotonSetLobbyName(LPSTR name );
FPSCR int PhotonIsWorkshopItemInstalled(LPSTR idString );
FPSCR int PhotonHasSubscriptionWorkshopItemFinished();
FPSCR void PhotonSendMyName();
FPSCR int PhotonIsOverlayActive();
FPSCR void PhotonWorkshopModeOff();
FPSCR void PhotonShowAgreement();
FPSCR void PhotonEndGame();
FPSCR void PhotonSendChat( LPSTR msg );
FPSCR void PhotonSendLobbyChat( LPSTR msg );
FPSCR LPSTR PhotonGetChat( void );
FPSCR int PhotonInkey( int scancode );
FPSCR int PhotonCheckSyncedAvatarTexturesWithServer();
FPSCR void PhotonSetMyAvatarHeadTextureName(LPSTR sAvatarTexture);
void PhotonAvatarClient();
void PhotonAvatarServer();
FPSCR int PhotonStrCmp( LPSTR s1, LPSTR s2 );
*/
