#ifndef __BCGHELPIDS_H
#define __BCGHELPIDS_H

// This is a part of the BCGControlBar Library
// Copyright (C) 1998-2000 BCGSoft Ltd.
// All rights reserved.
//
// This source code can be used, distributed or modified
// only under terms and conditions 
// of the accompanying license agreement.
//----------------
// By Sven Ritter:
//----------------

#define BCGCBHELP_OFFSET	0x41000

static const DWORD dwBCGResHelpIDs [] = 
{
	// Commands
	IDC_BCGBARRES_CATEGORY,						BCGCBHELP_OFFSET + IDC_BCGBARRES_CATEGORY,
	IDC_BCGBARRES_USER_TOOLS,					BCGCBHELP_OFFSET + IDC_BCGBARRES_USER_TOOLS,
	IDC_BCGBARRES_BUTTON_DESCR,					BCGCBHELP_OFFSET + IDC_BCGBARRES_BUTTON_DESCR,

	// Toolbar
	IDC_BCGBARRES_TOOLBAR_LIST,					BCGCBHELP_OFFSET + IDC_BCGBARRES_TOOLBAR_LIST,
	IDC_BCGBARRES_TEXT_LABELS,					BCGCBHELP_OFFSET + IDC_BCGBARRES_TEXT_LABELS,
	IDC_BCGBARRES_RESET,						BCGCBHELP_OFFSET + IDC_BCGBARRES_RESET,
	IDC_BCGBARRES_RESET_ALL,					BCGCBHELP_OFFSET + IDC_BCGBARRES_RESET_ALL,
	IDC_BCGBARRES_NEW_TOOLBAR,					BCGCBHELP_OFFSET + IDC_BCGBARRES_NEW_TOOLBAR,
	IDC_BCGBARRES_RENAME_TOOLBAR,				BCGCBHELP_OFFSET + IDC_BCGBARRES_RENAME_TOOLBAR,
	IDC_BCGBARRES_DELETE_TOOLBAR,				BCGCBHELP_OFFSET + IDC_BCGBARRES_DELETE_TOOLBAR,

	// Menu
	IDC_BCGBARRES_MENU_LIST,					BCGCBHELP_OFFSET + IDC_BCGBARRES_MENU_LIST,
	IDC_BCGBARRES_CONTEXT_MENU_LIST,			BCGCBHELP_OFFSET + IDC_BCGBARRES_CONTEXT_MENU_LIST,
	IDC_BCGBARRES_RESET_MENU,					BCGCBHELP_OFFSET + IDC_BCGBARRES_RESET_MENU,
	IDC_BCGBARRES_RESET_FRAME_MENU,				BCGCBHELP_OFFSET + IDC_BCGBARRES_RESET_FRAME_MENU,
	IDC_BCGBARRES_MENU_ANIMATION,				BCGCBHELP_OFFSET + IDC_BCGBARRES_MENU_ANIMATION,
	IDC_BCGBARRES_MENU_SHADOWS,					BCGCBHELP_OFFSET + IDC_BCGBARRES_MENU_SHADOWS,

	// Mouse
	IDC_BCGBARRES_LIST_VIEWS,					BCGCBHELP_OFFSET + IDC_BCGBARRES_LIST_VIEWS,
	IDC_BCGBARRES_NO_DBLCLIICK,					BCGCBHELP_OFFSET + IDC_BCGBARRES_NO_DBLCLIICK,
	IDC_BCGBARRES_USE_DBLCLIICK,				BCGCBHELP_OFFSET + IDC_BCGBARRES_USE_DBLCLIICK,
	IDC_BCGBARRES_LIST_OF_COMMANDS,				BCGCBHELP_OFFSET + IDC_BCGBARRES_LIST_OF_COMMANDS,

	// Keyboard
	IDC_BCGBARRES_CATEGORY,						BCGCBHELP_OFFSET + IDC_BCGBARRES_CATEGORY,
	IDC_BCGBARRES_COMMANDS_LIST,				BCGCBHELP_OFFSET + IDC_BCGBARRES_COMMANDS_LIST,
	IDC_BCGBARRES_VIEW_TYPE,					BCGCBHELP_OFFSET + IDC_BCGBARRES_VIEW_TYPE,
	IDC_BCGBARRES_CURRENT_KEYS_LIST,			BCGCBHELP_OFFSET + IDC_BCGBARRES_CURRENT_KEYS_LIST,
	IDC_BCGBARRES_NEW_SHORTCUT_KEY,				BCGCBHELP_OFFSET + IDC_BCGBARRES_NEW_SHORTCUT_KEY,
	IDC_BCGBARRES_ASSIGN,						BCGCBHELP_OFFSET + IDC_BCGBARRES_ASSIGN,
	IDC_BCGBARRES_REMOVE,						BCGCBHELP_OFFSET + IDC_BCGBARRES_REMOVE,
	IDC_BCGBARRES_RESET_SHORTCUTS,				BCGCBHELP_OFFSET + IDC_BCGBARRES_RESET_SHORTCUTS,

	// Options
	IDC_BCGBARRES_SHOW_TOOLTIPS,				BCGCBHELP_OFFSET + IDC_BCGBARRES_SHOW_TOOLTIPS,
	IDC_BCGBARRES_SHOW_TOOLTIPS_WITH_KEYS,		BCGCBHELP_OFFSET + IDC_BCGBARRES_SHOW_TOOLTIPS_WITH_KEYS,
	IDC_BCGBARRES_LARGE_ICONS,					BCGCBHELP_OFFSET + IDC_BCGBARRES_LARGE_ICONS,
	IDC_BCGBARRES_LOOK2000,						BCGCBHELP_OFFSET + IDC_BCGBARRES_LOOK2000,	
	IDC_BCGBARRES_SHOW_RECENTLY_USED_MENUS,		BCGCBHELP_OFFSET + IDC_BCGBARRES_SHOW_RECENTLY_USED_MENUS,
	IDC_BCGBARRES_SHOW_MENUS_DELAY,				BCGCBHELP_OFFSET + IDC_BCGBARRES_SHOW_MENUS_DELAY,
	IDC_BCGBARRES_RESET_USAGE_DATA,				BCGCBHELP_OFFSET + IDC_BCGBARRES_RESET_USAGE_DATA,

	0, 0};

#endif // __BCGHELPIDS_H
