//
// Runtime error strings for DarkEngine
//

#include "EXEBlock.h"
extern CEXEBlock CEXE;

void FillDarkErrors ( void )
{
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[0], "An unknown error has occurred");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1], "Broke from nested subroutine. Cannot resume program after CLI usage.");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[21], "The program tried to execute a function header declaration");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[51], "The index number you have used is bigger than the array size");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[52], "The index number you have used must be within the arrray");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[53], "The array is empty");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[54], "Array type is invalid");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[55], "Array specified must be a single dimension array for this type of command");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[101], "There was not enough memory to make such an array");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[102], "Unknown array error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[103], "The file is too large");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[104], "The file is invalid");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[105], "File does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[106], "File already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[107], "The string is to long");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[108], "Stack overflow error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[109], "Cannot make an array of that type");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[110], "Only positive numbers are allowed");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[111], "Divide by zero error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[112], "Illegal size error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[113], "Only positive numbers are allowed");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[114], "You must use a variable");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[115], "You must use a variable");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[116], "This command is now obsolete");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[117], "Cannot access the file because it is being used by another process");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[118], "Array does not exist or array subscript out of bounds");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[119], "Division by zero");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[300], "Unknown sprite error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[301], "Sprite number must be greater than zero");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[302], "Sprite does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[303], "Sprite backsave illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[304], "Sprite transparency illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[310], "Sprite rotation illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[311], "Sprite scale illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[312], "Sprite size illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[313], "Sprite angle illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[314], "Sprite alpha value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[315], "Sprite rgb value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[316], "Sprite animation delay value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[317], "Sprite vertex number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[318], "Sprite width illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[319], "Sprite height illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[320], "Sprite animation value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[321], "Sprite already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[500], "Unknown image error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[501], "Image number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[502], "Image does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[503], "Cannot grab image due to the area being too large");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[504], "Cannot grab image due to an illegal area");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[505], "Image is too large to be a texture");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[506], "Could not load image");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[507], "Cannot read an image currently locked by system");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1000], "Unknown bitmap error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1001], "Bitmap number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1002], "Bitmap does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1003], "Could not load bitmap");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1004], "Could not save bitmap");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1005], "Could not create bitmap");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1006], "Cannot delete bitmap zerp");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1007], "Bitmap numbers are identical");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1008], "Source bitmap is too large");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1009], "Bitmap zero is reserved");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1010], "Region has exceeded bitmap size");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1011], "Bitmap area is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1012], "Blur value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1013], "Fade value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1014], "Gamm value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1500], "Unknown screen error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1501], "Screen size is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1502], "Screen depth is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1503], "Screen mode is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1504], "Display cannot be created due to unknown Direct X error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1505], "Display using 16 bit is not supported by available hardware");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1506], "Display using 24 bit is not supported by available hardware");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1507], "Display using 32 bit is not supported by available hardware");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1508], "Display does not support selected method of vertex processing");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1509], "Display does not support selected method of backbuffer access");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1510], "Display cannot be initialized due to absent Direct X interface");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1511], "Display cannot be created due to invalid function parameters");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1512], "Display is not supported by available hardware");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1513], "Display cannot be created due to insufficient video memory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[1514], "24 bit depth not supported. Select either 16 or 32 bit mode");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2000], "Unknown animation error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2001], "Animation number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2002], "Could not load animation");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2003], "Animation already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2004], "Animation does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2005], "Animation volume value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2006], "Animation frequency value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2007], "Animation is already playing");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2008], "Animation is not playing");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2009], "Animation is already paused");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[2010], "Animation is not paused");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3000], "Unknown sound error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3001], "Sound number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3002], "Could not load sound");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3003], "Sound already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3004], "Sound does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3005], "Sound volume value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3006], "Sound frequency value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3007], "Sound pan value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3008], "Could not save sound");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3021], "Could not clone sound");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3022], "A sound must be specified");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3023], "A sound must be specified to clone	");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3201], "A speech engine cannot be found");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3500], "Unknown music error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3501], "Music number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3502], "Could not load music");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3503], "Music already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3504], "Music does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3505], "Music volume value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3506], "Music speed value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3507], "Music is not playing");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[3508], "Music track is illegal	");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[4001], "Unknown controller error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[4002], "A controller has not been selected");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[4101], "No force-feedback controller found");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[4102], "Magnitude value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[4103], "Duration value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[4104], "Angle value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5101], "Memblock range is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5102], "Memblock already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5103], "Memblock does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5104], "Could not create memblock");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5105], "Memblock position outside range");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5106], "Memblock size value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5107], "Not a memblock byte");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5108], "Not a memblock word");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[5109], "Not a memblock dword");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7000], "Unknown 3D error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7001], "Mesh number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7002], "Could not load mesh");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7003], "Mesh does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7004], "Mesh darken value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7005], "Mesh lighten value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7006], "Object number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7007], "Object already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7008], "Object does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7009], "Matrix already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7010], "Matrix number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7011], "Matrix dimensions illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7012], "Matrix segments illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7013], "Matrix does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7014], "Matrix height error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7015], "Matrix exceeds maximum size");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7016], "Matrix tile illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7017], "Matrix coordinates illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7018], "Could not load 3D object");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7019], "Object angle value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7020], "Too many limbs exist in the object");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7021], "Limb number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7022], "Cannot add a limb with that number");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7023], "Limb does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7024], "Limb already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7025], "Cannot link a limb to that number");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7026], "You must link limbs in chain sequence");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7027], "You can only link new limbs");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7028], "Mesh is too large for limb placement");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7029], "3D Memory Error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7030], "You must use the .DBO extension for a saved DBPro object");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7031], "Object fade value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7032], "Limb does not contain a mesh");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7101], "Particles object already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7102], "Particles object does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7103], "Unknown particles objects error");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7104], "Particle number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7105], "Particle must have an emission value greater than zero");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7126], "Could not create terrain");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7127], "Terrain already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7128], "Terrain does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7129], "Terrain data must be exactly square");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7130], "Terrain number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7151], "Could not load BSP file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7152], "BSP does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7153], "BSP already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7154], "BSP collision index must be between 1 and 24");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7201], "Camera number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7202], "Camera already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7203], "Camera does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7204], "Cannot create camera");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7205], "Cannot use camera zero");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7301], "Light number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7302], "Light already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7303], "Light does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7304], "Cannot create light	");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7305], "Cannot use light zero");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7601], "Animation frame number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7602], "Animation keyframe does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7603], "Animation speed value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7604], "Animation interpolation illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7605], "Cannot append to the object");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7606], "Append can only add to end of object animation");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7607], "Failed to compile CSG file from X File");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7701], "Vertex shader number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7702], "Vertex shader count illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7703], "Cannot create vertex shader");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7704], "Vertex shader stream position illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7705], "Vertex shader data illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7706], "Vertex shader stream illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7707], "Vertex shader cannot be assembled");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7708], "Vertex shader is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7721], "Effect number is illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7722], "Effect does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7723], "Effect already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7801], "Vector does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7802], "Matrix4 does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7901], "Fogging effect is not available");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7911], "Ambient percentage value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7912], "Camera range value illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7931], "The source must be a 3DS file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[7932], "The destination must be an X file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8001], "Could not scan current directory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8002], "There are no more files in directory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8003], "Could not find path");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8021], "Could not make file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8022], "Could not delete file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8023], "Could not copy file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8024], "Could not rename file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8025], "Could not move file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8101], "Could not create directory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8102], "Could not delete directory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8103], "Could not execute file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8201], "Could not open file for reading");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8202], "Could not open file for writing");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8203], "File is already open");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8204], "File is not open");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8211], "Cannot read from file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8212], "Cannot write to file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8213], "File number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8301], "Could not connect to FTP");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8302], "Cannot find FTP path");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8303], "Cannot put FTP file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8304], "Cannot delete FTP file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8305], "Cannot get FTP file");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8501], "Could not establish multiplayer connection");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8502], "Could not find session");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8503], "Could not setup session");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8504], "Could not create net level");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8505], "Could not join net level");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8506], "Could not send net level message");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8507], "Only 2 to 255 players can be specified");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8508], "Player name required");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8509], "Game name required");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8510], "Connection number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8511], "Session number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8512], "Player number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8513], "Not currently in net game session");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8514], "Player number does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8515], "Session number does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8516], "Player could not be created");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8517], "Player could not be deleted");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[8518], "Too many players in session");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9001], "Checklist number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9002], "Checklist number illegal");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9003], "Checklist contains only numbers");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9004], "Checklist contains only strings");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9005], "Checklist does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9011], "Could not find the device");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9012], "Could not get texture memory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9013], "Could not get video memory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9014], "Could not get system memory");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9701], "Could not load DLL");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9702], "DLL does not exist");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9703], "DLL already exists");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9704], "Could not call DLL function");
	strcpy ( CEXE.m_pRuntimeErrorStringsArray[9705], "Index number illegal");
}
